name: hondooye_error_handler
description: A useful error handler
version: 0.0.2
repository: "https://github.com/Doohyeon-Kim/hondooye-error-handler.git"

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  hondooye_logger: ^0.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
